spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false #Hibernate: ile baslayan loglar, basinda tarih yok
    generate-ddl: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:testdb
    #url=jdbc:h2:file:/data/demo
    username: h2-user
    password: h2-pass
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

